name: memoryscrapbook
description: "A Memory Scrapbook to store daily memories."

publish_to: 'none'
version: 1.0.0+1
environment:
   sdk: '>=3.3.0 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # Image handling
  image_picker: ^1.0.4

  # Permissions
  permission_handler: ^12.0.0+1

  # Audio recording
  record: ^6.0.0

  # For date/time formatting
  intl: ^0.20.2

  # The following adds the Cupertino Icons font.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true
